<<<<<<< HEAD
=======
AllCops:
  Exclude:
    - 'demo.rb'

>>>>>>> 5706b0a623a4d62c09b4e13ae4a42db54b50f62d
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 110

Metrics/LineLength:
  Max: 100
